"""Add hashed_password to User

Revision ID: 5c811c7e6b55
Revises: b6cebbf22361
Create Date: 2025-03-11 18:23:18.819019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c811c7e6b55'
down_revision = 'b6cebbf22361'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
