"""add user-category preference table

Revision ID: 664be28d6438
Revises: 5c811c7e6b55
Create Date: 2025-04-13 14:55:42.507478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '664be28d6438'
down_revision = '5c811c7e6b55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usercategorypreference',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('notification_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usercategorypreference')
    # ### end Alembic commands ###
